[package]
name = "blackrust_v0"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "*"
#xrandr = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
image-base64 = "*"
regex = "1"
toml = "*"
blackrust_lib = {path = "blackrust_lib"}

[[bin]]
name = "blackrust"
path = "src/dm.rs"