[[profile_vec]]
id = "ee6cca93-0ccc-44e4-9076-a544bfcb3da0"
name = "RDP Test"

[[profile_vec.network_settings]]
gateway = ""
hostname = ""
interface = ""
ipv4 = ""
ipv6 = ""

[profile_vec.network_settings.dns]
name_servers = [""]
search_domains = [""]

[profile_vec.network_settings.vpn]

[profile_vec.conn_settings]
extra_settings = ""
ip_fqdn = ""

[profile_vec.conn_settings.protocol]
name = "RDP"
port = 3389
port_protocol = "TCP"

[[profile_vec]]
id = "8fa7210e-d40b-4e62-95e4-e1d7b46b1482"
name = "XDMCP Test"

[[profile_vec.network_settings]]
gateway = ""
hostname = ""
interface = ""
ipv4 = ""
ipv6 = ""

[profile_vec.network_settings.dns]
name_servers = [""]
search_domains = [""]

[profile_vec.network_settings.vpn]

[profile_vec.conn_settings]
extra_settings = ""
ip_fqdn = ""

[profile_vec.conn_settings.protocol]
name = "XDMCP"
port = 117
port_protocol = "UDP"

[[profile_vec]]
id = "516c03d0-46f4-403e-a30d-66b017048dcc"
name = "Local session test"

[[profile_vec.network_settings]]
gateway = ""
hostname = ""
interface = ""
ipv4 = ""
ipv6 = ""

[profile_vec.network_settings.dns]
name_servers = [""]
search_domains = [""]

[profile_vec.network_settings.vpn]

[profile_vec.conn_settings]
extra_settings = ""
ip_fqdn = ""

[profile_vec.conn_settings.protocol]
name = ""
port = 0
port_protocol = "None"
