name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
            sudo apt-get update
            sudo DEBIAN_FRONTEND=noninteractive apt-get -y install rustc librust-pango-dev librust-atk-dev libsoup2.4-dev libwebkit2gtk-4.0-dev npm xserver-xorg xserver-xorg-video-dummy
    - name: Make & Run X11
      run: |
            make build
            sudo X :0 -config .github/workflows/xorg-dummy.conf &
    - name: Run tests
      run: DISPLAY=:0 cargo test --verbose