name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_PATH: '/usr/lib/pkgconfig'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
            sudo apt-get update
            sudo apt-get install librust-pango-dev librust-atk-dev libsoup2.4-dev libwebkit2gtk-4.0-dev npm
    - name: Build
      run: |
            cd src/web
            npm install
            cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
