name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
            apt-get update
            export DEBIAN_FRONTEND=noninteractive
            apt-get -y install librust-pango-dev librust-atk-dev libsoup2.4-dev libwebkit2gtk-4.0-dev npm xserver-xorg
    - name: Build
      run: |
            /usr/X11/bin/startx
            cd src/web
            npm install
            cargo build --verbose
    - name: Run tests
      run: cargo test --verbose